/**
 * FluentHour static build copier
 * - Treat repo as "static-first": already-built files in repo root.
 * - Netlify build step copies them into dist/ (publish directory).
 */
import fs from 'node:fs';
import path from 'node:path';

const ROOT = process.cwd();
const DIST = path.join(ROOT, 'dist');

const SKIP = new Set([
  'node_modules',
  'dist',
  '.git',
  '.netlify',
  'package-lock.json', // regenerated by npm ci anyway
  'package.json',
  'scripts',
  'README.md',
  'RUN_DEV.ps1',
]);

function rmrf(p) {
  if (!fs.existsSync(p)) return;
  fs.rmSync(p, { recursive: true, force: true });
}

function copyRecursive(src, dst) {
  const stat = fs.statSync(src);
  if (stat.isDirectory()) {
    fs.mkdirSync(dst, { recursive: true });
    for (const name of fs.readdirSync(src)) {
      copyRecursive(path.join(src, name), path.join(dst, name));
    }
    return;
  }
  fs.mkdirSync(path.dirname(dst), { recursive: true });
  fs.copyFileSync(src, dst);
}

rmrf(DIST);
fs.mkdirSync(DIST, { recursive: true });

for (const name of fs.readdirSync(ROOT)) {
  if (SKIP.has(name)) continue;
  copyRecursive(path.join(ROOT, name), path.join(DIST, name));
}

console.log('Copied static site into dist/.');
